[package]
name = "rustmvc"
version = "0.1.0"
authors = ["木瓜丸 <boke0@eugensite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.2.2"
