[package]
name = "migrator"
version = "0.1.0"
authors = ["木瓜丸 <boke0@eugensite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
